# Generated by Django 2.2.4 on 2020-02-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='quit_date',
            field=models.DateTimeField(),
        ),
    ]
